name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        rustup component add rust-src
        rustup component add llvm-tools-preview
        cargo install bootimage
    - name: Build
      run: cargo bootimage
    - name: Run tests
      run: cargo test --verbose
